### ISSUE TITLE
conf2struct possibly still broken with libconfig 1.7.3

### ISSUE THREAD

**Issue by wak-google** [yrutschle/conf2struct#13]
```
| NOTE: make -j 72 DESTDIR=/build PREFIX=/usr USELIBCAP=1 USELIBBSD=1 USESYSTEMD=1 sslh-conf.h
| Makefile:74: warning: ignoring prerequisites on suffix rule definition
| conf2struct sslhconf.cfg
| [WARN] Settings is null in get_hashvalue at /build/usr/bin/conf2struct line 52.
| Use of uninitialized value $header in concatenation (.) or string at /build/usr/bin/conf2struct line 1780.
| Use of uninitialized value $header in concatenation (.) or string at /build/usr/bin/conf2struct line 1780.
| : No such file or directory
| make: *** [Makefile:84: sslh-conf.h] Error 2
```

I don't run into these errors if I revert the libconfig change. This is using conf2struct at 06ddd9273f14dadd5f7b4cf144177ffa6a29f105

**Comment by yrutschle** [comment]
How about with -j 1 ?

**Comment by wak-google** [comment]
It's the same even if I just execute `conf2struct sslhconf.cfg` directly.

**Comment by yrutschle** [comment]
ok, the call to fetch_hashref("/") translates, through the Perl API, to the same issue as I had [here](https://github.com/hyperrealm/libconfig/issues/196) with libconfig 1.7.3.
The Perl API is lacking a way to retrieve the root element, so I worked around that.
