### ISSUE TITLE
Missing Libconfig.pm

### ISSUE THREAD

**Issue by utoni** [yrutschle/conf2struct#14]
I am trying to recreate some structs for `sslh`. But I am getting an error about a missing perl module.

```
Can't locate Conf/Libconfig.pm in @INC (you may need to install the Conf::Libconfig module) (@INC contains: /usr/lib/perl5/5.34/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.34/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.34/core_perl /usr/share/perl5/core_perl) at ./conf2struct line 32.
BEGIN failed--compilation aborted at ./conf2struct line 32.
```
Installing `libconfig(-dev)` did not solve this issue. I've tried it on Arch and Debian.
What package / perl module do I have to install?

**Comment by yrutschle** [comment]
Does INSTALL.pm not help?
It is the Perl Libconfig support that is missing.


Apr 27, 2022 23:40:26 Toni ***@***.***>:

**Comment by utoni** [comment]
It did. Some tests during cpan installation failed. At least on Arch I need to use `-f`.

Thanks!
